language: go
sudo: true
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all GO=$(which go)
    - stage: Run Test Coverage
      script: make cover GO=$(which go)
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release GO=$(which go)
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/netns-linux-arm
          - cross/netns-linux-arm.md5
          - cross/netns-linux-arm.sha256
          - cross/netns-linux-arm64
          - cross/netns-linux-arm64.md5
          - cross/netns-linux-arm64.sha256
          - cross/netns-linux-amd64
          - cross/netns-linux-amd64.md5
          - cross/netns-linux-amd64.sha256
          - cross/netns-linux-386
          - cross/netns-linux-386.md5
          - cross/netns-linux-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "klR3qNxtu9bRmrmpLQ00CJPh71rboALatv0Q8SlpHuU3MOzcCclPKVHNomVw07cpORBBJXZyJ/tCDMYj2dMraJ7HE/z6Hp7XHEdlkhonOGh/uyHeziFss3MmxcDf6o/iLAjGZX3VKklrf9h2/pBHvpjKKFExDMNOpJK7YdXxV96rpXo3bGygFAHGyiP4cnDL33vlZ97a4Wofa8bg/gCftmxqMpHlJoP/MCqAYYDLYxxjqOgA0DRxIjLsvkpxzzCyg9TE4vVoz6g//ZEWtI4KjbW1Xzh/F2pNOTNXoJVgREhcumJqG8JinRhoXzbtxhg+9/aPm9In+gSa7pXrwf1g0x3MCGKR2M3VYM4qoA3DTRRo1kUIugDMi4gI1D9V8w/kLiGM8GFkZSM5zQg/HzH2wAW79rkrv9M1UpAww9pR09afrWv8KypHvyJGhF2vtUuQCxlzo3xr8RiiXVdSjdMlNdO7SJ6iIOFygPsXUbye9htpAkebaZiUfeDSoxRlUbxb3P387l3jVGfkuBOsSW0NPyrKO1S/QkbJql/4ZYNDB8hjPBSPpq+7WIR8hSn7UrHfsg/gheXugW8W/zQHlmJjUYTDwO++XksfrkcoT262GC9nnD81jYFHmcf13KUGeRn1vvbExbHVsxJVlHsjyfxxhkelHpuh4mxSvuJgeKjjUz8="
